export const ROUTES = {
    HOME_PAGE: "/home",
    CART_PAGE: "/cart",
    CHECKOUT_PAGE: "/checkout",
    CONTACT_PAGE: "/contact",
    SHOP_DETAIL_PAGE: "/products/:productId",
    SHOP_PAGE: "/products",
    TESTIMONIAL_PAGE: "/testimonial",
    PAGE_404: "/page404",
    DRY_PAGE: "/shop/drypage",
    WET_PAGE: "/shop/wetpage",
    SALENREFUND_PAGE: '/saleandrefund',
    PRIVACYPOLICY_PAGE: "/privacypolicy",
    TERMOFUSE_PAGE: "/termofuse",
    LOGIN_PAGE: "/login",
    REGISTER_PAGE: "/register",
    WHYPPLIKEUS_PAGE: "/whypplikeus",
    ABOUTUS_PAGE: "/aboutus",
    FAQ_PAGE: "/faq",
    WISHLIST_PAGE: "/wishlist",
    ACCOUNT_PAGE: "/account",
    CHANGEPASS_ACCOUNT_PAGE: "/account/changepass",
    HISTORYPURCHASE_ACCOUNT_PAGE: "/account/historypurchase"
}